include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - avoid_print
    - prefer_single_quotes
    - cancel_subscriptions
    - close_sinks
    - empty_statements
    - hash_and_equals
    - no_duplicate_case_values
    - unnecessary_await_in_return

