// Regenerates `lib/src/version.dart` from the `version:` field in
// `pubspec.yaml`. Run from the package root:
//
//   dart run tool/sync_version.dart
//
// Enforced by `test/version_sync_test.dart` — CI fails if the two drift.

import 'dart:io';

void main() {
  final pubspec = File('pubspec.yaml');
  if (!pubspec.existsSync()) {
    stderr.writeln('pubspec.yaml not found; run from the package root.');
    exit(1);
  }
  final version = _parseVersion(pubspec.readAsStringSync());
  if (version == null) {
    stderr.writeln('Could not locate `version:` in pubspec.yaml.');
    exit(1);
  }

  final out = File('lib/src/version.dart');
  out.writeAsStringSync(_render(version));
  stdout.writeln('version.dart ← $version');
}

String? _parseVersion(String pubspecYaml) {
  final match = RegExp(
    r'^version:\s*(.+?)\s*$',
    multiLine: true,
  ).firstMatch(pubspecYaml);
  return match?.group(1);
}

String _render(String version) =>
    '''
// GENERATED by tool/sync_version.dart — do not edit.
// Run `dart run tool/sync_version.dart` after bumping `pubspec.yaml`.

/// Version of the `synheart_core` Flutter SDK package.
///
/// Kept in sync with the `version:` field in pubspec.yaml. Surfaced so host
/// apps can display the SDK version in About / diagnostics screens without
/// having to ship the lock file as an asset.
const String synheartCoreVersion = '$version';
''';
